In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
# Load the dataset
df = pd.read_csv('C:/Users/AHVINAV//ML-Python/Final Evaluation/Loan.csv',header = 0)

In [3]:
df.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male     Yes          1      Graduate            No             4583   
1   Male     Yes          0      Graduate           Yes             3000   
2   Male     Yes          0  Not Graduate            No             2583   
3   Male      No          0      Graduate            No             6000   
4   Male     Yes          0  Not Graduate            No             2333   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0             1508.0         128             360.0             1.0   
1                0.0          66             360.0             1.0   
2             2358.0         120             360.0             1.0   
3                0.0         141             360.0             1.0   
4             1516.0          95             360.0             1.0   

  Property_Area Loan_Status  
0         Rural           N  
1         Urban           Y  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y

#### Imputing Missing Value

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381 entries, 0 to 380
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             376 non-null    object 
 1   Married            381 non-null    object 
 2   Dependents         373 non-null    object 
 3   Education          381 non-null    object 
 4   Self_Employed      360 non-null    object 
 5   ApplicantIncome    381 non-null    int64  
 6   CoapplicantIncome  381 non-null    float64
 7   LoanAmount         381 non-null    int64  
 8   Loan_Amount_Term   370 non-null    float64
 9   Credit_History     351 non-null    float64
 10  Property_Area      381 non-null    object 
 11  Loan_Status        381 non-null    object 
dtypes: float64(3), int64(2), object(7)
memory usage: 35.8+ KB


##### Missing Values
##### Numical
* Loan_Amount_Term, Credit_History
##### categorical_cols
* Gender, Dependents, Self_Employed

In [5]:
# Fill missing values for numerical columns with the mean
df.Loan_Amount_Term=df.Loan_Amount_Term.fillna(df.Loan_Amount_Term.mean())
df.Credit_History=df.Credit_History.fillna(df.Credit_History.mean())

In [6]:
# Fill missing values for categorical columns with the mode
df.Gender = df.Gender.fillna(df.Gender.mode()[0])
df.Dependents = df.Dependents.fillna(df.Dependents.mode()[0])
df.Self_Employed = df.Self_Employed.fillna(df.Self_Employed.mode()[0])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381 entries, 0 to 380
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             381 non-null    object 
 1   Married            381 non-null    object 
 2   Dependents         381 non-null    object 
 3   Education          381 non-null    object 
 4   Self_Employed      381 non-null    object 
 5   ApplicantIncome    381 non-null    int64  
 6   CoapplicantIncome  381 non-null    float64
 7   LoanAmount         381 non-null    int64  
 8   Loan_Amount_Term   381 non-null    float64
 9   Credit_History     381 non-null    float64
 10  Property_Area      381 non-null    object 
 11  Loan_Status        381 non-null    object 
dtypes: float64(3), int64(2), object(7)
memory usage: 35.8+ KB


##### create dummy variables

In [8]:
df.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male     Yes          1      Graduate            No             4583   
1   Male     Yes          0      Graduate           Yes             3000   
2   Male     Yes          0  Not Graduate            No             2583   
3   Male      No          0      Graduate            No             6000   
4   Male     Yes          0  Not Graduate            No             2333   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0             1508.0         128             360.0             1.0   
1                0.0          66             360.0             1.0   
2             2358.0         120             360.0             1.0   
3                0.0         141             360.0             1.0   
4             1516.0          95             360.0             1.0   

  Property_Area Loan_Status  
0         Rural           N  
1         Urban           Y  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y

In [9]:
# One-hot encoding
df = pd.get_dummies(df, drop_first=True,dtype='int')

In [10]:
df.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             4583             1508.0         128             360.0   
1             3000                0.0          66             360.0   
2             2583             2358.0         120             360.0   
3             6000                0.0         141             360.0   
4             2333             1516.0          95             360.0   

   Credit_History  Gender_Male  Married_Yes  Dependents_1  Dependents_2  \
0             1.0            1            1             1             0   
1             1.0            1            1             0             0   
2             1.0            1            1             0             0   
3             1.0            1            0             0             0   
4             1.0            1            1             0             0   

   Dependents_3+  Education_Not Graduate  Self_Employed_Yes  \
0              0                       0                  0   
1              0                       0                  1   
2              0                       1                  0   
3              0                       0                  0   
4              0                       1                  0   

   Property_Area_Semiurban  Property_Area_Urban  Loan_Status_Y  
0                        0                    0              0  
1                        0                    1              1  
2                        0                    1              1  
3                        0                    1              1  
4                        0                    1              1

#### Identify and handle outliers using IQR method

In [11]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       381.000000         381.000000  381.000000        381.000000   
mean       3579.845144        1277.275381  104.986877        340.864865   
std        1419.813818        2340.818114   28.358464         67.549811   
min         150.000000           0.000000    9.000000         12.000000   
25%        2600.000000           0.000000   90.000000        360.000000   
50%        3333.000000         983.000000  110.000000        360.000000   
75%        4288.000000        2016.000000  127.000000        360.000000   
max        9703.000000       33837.000000  150.000000        480.000000   

       Credit_History  Gender_Male  Married_Yes  Dependents_1  Dependents_2  \
count      381.000000   381.000000   381.000000    381.000000    381.000000   
mean         0.837607     0.776903     0.598425      0.136483      0.154856   
std          0.354459     0.416870     0.490861      0.343752      0.362243   
min          0.000000     0.000000     0.000000      0.000000      0.000000   
25%          1.000000     1.000000     0.000000      0.000000      0.000000   
50%          1.000000     1.000000     1.000000      0.000000      0.000000   
75%          1.000000     1.000000     1.000000      0.000000      0.000000   
max          1.000000     1.000000     1.000000      1.000000      1.000000   

       Dependents_3+  Education_Not Graduate  Self_Employed_Yes  \
count     381.000000              381.000000         381.000000   
mean        0.073491                0.270341           0.091864   
std         0.261284                0.444720           0.289213   
min         0.000000                0.000000           0.000000   
25%         0.000000                0.000000           0.000000   
50%         0.000000                0.000000           0.000000   
75%         0.000000                1.000000           0.000000   
max         1.000000                1.000000           1.000000   

       Property_Area_Semiurban  Property_Area_Urban  Loan_Status_Y  
count               381.000000           381.000000     381.000000  
mean                  0.391076             0.330709       0.711286  
std                   0.488633             0.471087       0.453761  
min                   0.000000             0.000000       0.000000  
25%                   0.000000             0.000000       0.000000  
50%                   0.000000             0.000000       1.000000  
75%                   1.000000             1.000000       1.000000  
max                   1.000000             1.000000       1.000000

In [12]:
# Calculate Q1 (25th percentile) and Q3 (75th percentile)
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
# Calculate IQR (Interquartile Range)
IQR = Q3 - Q1
# Values below=> lower_bound-> Q1 - 1.5 * IQR or above => upper_bound -> Q3 + 1.5 * IQR are considered outliers.
lower_bound = Q1 - 1.5 * IQR 
upper_bound = Q3 + 1.5 * IQR 

In [13]:
# Remove outliers
df = df[~((df < lower_bound) | (df > upper_bound)).any(axis=1)]

#### Test-Train Split

In [14]:
# Dependent- Independent Data split (X-y Split)
X = df.drop('Loan_Status_Y', axis=1)
y = df['Loan_Status_Y']

In [15]:
# Split the dataset into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42)

#### Logistic Regression

In [16]:
#Train the Logistic Regression 
from sklearn.linear_model import LogisticRegression
clf_lrs = LogisticRegression()
clf_lrs.fit(X_train,y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [17]:
# Predict values using trained model
y_pred_lr = clf_lrs.predict(X_test)

In [18]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score
confusion_matrix(y_test, y_pred_lr)

array([[ 0,  5],
       [ 0, 17]], dtype=int64)

In [19]:
# Evaluate the Performance
accuracy_score_lr=accuracy_score(y_test, y_pred_lr)
precision_score_lr=precision_score(y_test, y_pred_lr)
recall_score_lr = recall_score(y_test, y_pred_lr)

#### LDA/Linear Discriminant Analysis

In [20]:
# Train the LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
clf_lda = LinearDiscriminantAnalysis()
clf_lda.fit(X_train,y_train)

LinearDiscriminantAnalysis()

In [21]:
# Predict values using trained model
y_pred_lda = clf_lda.predict(X_test) 


In [22]:
confusion_matrix(y_test, y_pred_lda)

array([[ 0,  5],
       [ 0, 17]], dtype=int64)

In [23]:
# Evaluate the Performance
accuracy_score_lda=accuracy_score(y_test, y_pred_lda)
precision_score_lda=precision_score(y_test, y_pred_lda)
recall_score_lda = recall_score(y_test, y_pred_lda)

#### K-Nearest Neighbors/KNN

In [24]:
#Train the KNN 
from sklearn.neighbors import KNeighborsClassifier
clf_knn = KNeighborsClassifier()
clf_knn.fit(X_train, y_train)

KNeighborsClassifier()

In [25]:
# Predict values using trained model
y_pred_knn = clf_knn.predict(X_test)


In [26]:
confusion_matrix(y_test,y_pred_knn)

array([[ 0,  5],
       [ 0, 17]], dtype=int64)

In [27]:
# Evaluate the Performance
accuracy_score_knn=accuracy_score(y_test, y_pred_knn)
precision_score_knn=precision_score(y_test, y_pred_knn)
recall_score_knn=recall_score(y_test, y_pred_knn)

#### Decision Tree 

In [28]:
# Train the Decision Tree Classifier
from sklearn import tree
clftree = tree.DecisionTreeClassifier()
clftree.fit(X_train, y_train)

DecisionTreeClassifier()

In [29]:
# Predict values using trained model
y_pred_tree = clftree.predict(X_test)

In [30]:
confusion_matrix(y_test, y_pred_tree)

array([[ 2,  3],
       [ 1, 16]], dtype=int64)

In [31]:
# Evaluate the Performance
accuracy_score_tree = accuracy_score(y_test, y_pred_tree)
precision_score_tree=precision_score(y_test, y_pred_tree)
recall_score_tree=recall_score(y_test, y_pred_tree)

In [32]:
# Compare the performance of different classifiers
performance_comparison = pd.DataFrame({
    'Classifier': ['Logistic Regression', 'Linear Discriminant Analysis', 'K-Nearest Neighbors', 'Decision Tree'],
    'Accuracy Score': [accuracy_score_lr, accuracy_score_lda, accuracy_score_knn, accuracy_score_tree],
    'Precision Score': [precision_score_lr, precision_score_lda, precision_score_knn, precision_score_tree],
    'Recall Score': [recall_score_lr, recall_score_lda, recall_score_knn, recall_score_tree],
})

# Display the comparison
print(performance_comparison)

                     Classifier  Accuracy Score  Precision Score  Recall Score
0           Logistic Regression        0.772727         0.772727      1.000000
1  Linear Discriminant Analysis        0.772727         0.772727      1.000000
2           K-Nearest Neighbors        0.772727         0.772727      1.000000
3                 Decision Tree        0.818182         0.842105      0.941176


##### Data Preparation:

* Load the dataset.
* Handle missing values.
* Convert categorical variables into dummy variables.
* Remove outliers using the IQR method.
    
##### Model Training and Evaluation:

* Train and evaluate four classifiers: Logistic Regression, Linear Discriminant Analysis (LDA), K-Nearest Neighbors (KNN), and Decision Tree.
* Calculate accuracy, precision, and recall scores for each model.

##### Comparison:

* Create a DataFrame to compare the performance metrics of all classifiers.
* Display the comparison.

* Decision Tree stands out as the best-performing model overall because it has the highest accuracy and precision. 
Although it has slightly lower recall, its overall performance in terms of accuracy and precision is superior to the other models.